### ISSUE TITLE
parallel / parallelLimit / control flow

### ISSUE THREAD

**Issue by evgenzvg** [webquarx/design-patterns#13]
[parallel](http://caolan.github.io/async/v3/docs.html#parallel)

- [x] run the tasks in parallel
- [ ] how to use synchronously
- [x] stops others if there is an error
- [ ] do not stop on errors
- [ ] continue if fail only selected tasks
- [x] limit concurrency of tasks
- [x] limit each task with a timeout
- [x] results are in an array in the same order
- [ ] use an object instead of an array
- [ ] return result in an object with the same keys

Run the tasks collection of functions in parallel, without waiting until the previous function has completed. If any of the functions pass an error to its callback, the main callback is immediately called with the value of the error. Once the tasks have completed, the results are passed to the final callback as an array.

**Note**: parallel is about kicking-off I/O tasks in parallel, not about parallel execution of code. If your tasks do not use any timers or perform any I/O, they will actually be executed in series. Any synchronous setup sections for each task will happen one after the other. JavaScript remains single-threaded.

**Hint**: Use [reflect](http://caolan.github.io/async/v3/docs.html#reflect) to continue the execution of other tasks when a task fails.

**Hint**: Use timeout to limit execution time

It is also possible to use an object instead of an array. Each property will be run as a function and the results will be passed to the final callback as an object instead of an array. This can be a more readable way of handling results from async.parallel.

**Parameters**

**tasks**: Array | Iterable | AsyncIterable | Object
A collection of [async functions](http://caolan.github.io/async/v3/global.html) to run. Each async function can complete with any number of optional result values.

**limit**: number
The maximum number of async operations at a time.

![Image](https://github.com/webquarx/design-patterns/assets/142693046/7578cc3a-0c6d-484a-b8e6-37f7c9ef2aca)
